name: Deploy pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          keep_history: false
          build_dir: dist
          commit_message: "Pages from: ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
