name: Deploy pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          keep_history: false
          build_dir: source
          commit_message: "Pages from: ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
